### PR TITLE
Fix #127 and #129

### LINKED ISSUE #127: Division, Conference
Given a team name or team ID, is there a way to extract their conference and division from the nfldb database?

### PR DESCRIPTION
**Pull request by bmay2**

### CODE REVIEW

**Comment by BurntSushi** [comment]
@bmay2 Thanks! Could you please add a helpful commit message describing the change?

**Comment by bmay2** [comment]
No problem! Let me know if you need anything else.

**Comment by BurntSushi** [comment]
Much better, thanks very much! :-)

**Comment by BurntSushi** [comment]
@bmay2 Sorry, but I didn't review this PR closely enough. You can't modify existing migrations to add new fields to a table. You have to create *new* migrations that modify existing databases, otherwise it makes the whole idea of migrations pointless.

Unfortunately, I had to revert this PR because of it. I'd be happy to accept a new one with migrations done right. (Let me know if you need help with that!)

**Comment by bmay2** [comment]
So I should add my changes to a new _migrate_# method in db.py?

**Comment by BurntSushi** [comment]
Yup. Just use a number that is 1 greater than the previous and it should just work. You'll need to issue `ALTER TABLE` commands.

**Comment by bmay2** [comment]
I think I'm going to create two new pull requests for this - one for Fix #127 and one for Fix #129. Sound good?

**Comment by BurntSushi** [comment]
@bmay2 Perfect!

**Pull request merged**
