### PR TITLE
Fixed bug to ensure LA Rams don't show up as UNK

### PR DESCRIPTION
**Pull request by blitzstudios**

### CODE REVIEW

**Comment by blitzstudios** [comment]
wups looks like u fixed it!

**Comment by pla1** [comment]
I updated all game rows to LA where team was UNK. UNK pops back in for gamekey 56916 after running nfldb-update.

**Comment by pla1** [comment]
Should have ran:
sudo pip install nfldb --upgrade
sudo nfldb-update --update-schedules

Sorry for the noise. Thanks!

**Comment by andr3w321** [comment]
I had to run `DELETE FROM game WHERE home_team = 'UNK' OR away_team = 'UNK';` in postgres and then re-run `nfldb-update` after the bug fix.

**Pull request closed without merging**
